### ISSUE TITLE
no limitation for "%s" while calling scanf()

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [oracle/dtrace-linux-kernel#1]
https://github.com/oracle/dtrace-linux-kernel/blob/4d02aa8e6e28c9c087142123eb2fd6f6d367c336/arch/s390/tools/gen_opcode_table.c#L158

**Comment by nickalcock** [comment]
Inappropriate report: we are tracking upstream, and DTrace contains no code relating to arch/s390.
