### ISSUE TITLE
The return value of 'sscanf()' should be checked

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [oracle/dtrace-linux-kernel#2]
https://github.com/oracle/dtrace-linux-kernel/blob/4d02aa8e6e28c9c087142123eb2fd6f6d367c336/tools/power/cpupower/bench/main.c#L106

**Comment by nickalcock** [comment]
Inappropriate report: we are tracking upstream, and DTrace contains no code relating to tools/cpupower.
